import { gammaBinMasses } from '../math/probability'
import { createInitialTinyModel, evaluateTinyModel } from '../math/transformer'
import type {
  AttentionObject,
  BarycentricObject,
  GeometryObject,
  NumberTheoryObject,
  SimplexObject,
  TrainingObject,
  WorldObject,
  WorldState,
} from './types'

export const HERO_EQUATION_ID = 'eq_integral'
export const HERO_GRAPH_ID = 'graph_integrand'
export const SOURCE_IMAGE_ID = 'source'
export const OPENING_FRAME_ID = 'gamma_clinic_frame'
export const OPENING_ATTEMPT_ID = 'opening_attempt'
export const OPENING_CORRECTION_ID = 'opening_correction'

const frame = (
  id: string,
  title: string,
  childIds: string[],
  x: number,
  y: number,
  width = 820,
  height = 540,
): WorldObject => ({
  id,
  kind: 'frame',
  title,
  childIds,
  bounds: { x, y, width, height },
  rotation: 0,
  author: 'human',
  opacity: 1,
})

export function createSeedWorld(): WorldState {
  const shape = 4.5
  const binEdges: [number, number, number, number] = [0, 3.15, 6.075, 16]
  const bridgeMasses = gammaBinMasses(shape, binEdges)
  const model = createInitialTinyModel(bridgeMasses)
  const initialPass = evaluateTinyModel(model, bridgeMasses)

  const attention: AttentionObject = {
    id: 'attention_mechanism',
    kind: 'attention',
    model,
    bridgeMasses,
    temperature: 1,
    bounds: { x: 1355, y: 138, width: 790, height: 430 },
    rotation: 0,
    author: 'agent',
    opacity: 1,
  }
  const training: TrainingObject = {
    id: 'training_panel',
    kind: 'training',
    model: createInitialTinyModel(bridgeMasses),
    linkedAttentionId: attention.id,
    step: 0,
    lossHistory: [initialPass.loss],
    probabilityHistory: [initialPass.targetProbability],
    learningRate: 0,
    bounds: { x: 2455, y: 138, width: 790, height: 430 },
    rotation: 0,
    author: 'human',
    opacity: 1,
  }
  const barycentric: BarycentricObject = {
    id: 'barycentric_geometry',
    kind: 'barycentric',
    vertices: [{ x: 110, y: 330 }, { x: 650, y: 330 }, { x: 385, y: 60 }],
    labels: ['V₁', 'V₂', 'V₃'],
    weights: bridgeMasses,
    linkedAttentionId: attention.id,
    bounds: { x: -815, y: 820, width: 750, height: 430 },
    rotation: 0,
    author: 'agent',
    opacity: 1,
  }
  const invariantPoint = {
    x: bridgeMasses[0] * 95 + bridgeMasses[1] * 560 + bridgeMasses[2] * 270,
    y: bridgeMasses[0] * 325 + bridgeMasses[1] * 330 + bridgeMasses[2] * 62,
  }
  const similarity: GeometryObject = {
    id: 'geometry_construction',
    kind: 'geometry',
    accent: '#7c5cff',
    bounds: { x: 250, y: 820, width: 760, height: 430 },
    rotation: 0,
    author: 'agent',
    opacity: 1,
    primitives: [
      { kind: 'point', id: 'O', at: { x: 350, y: 220 }, label: 'O', draggable: true },
      { kind: 'point', id: 'A', at: { x: 95, y: 325 }, label: 'A', draggable: true },
      { kind: 'point', id: 'B', at: { x: 560, y: 330 }, label: 'B', draggable: true },
      { kind: 'point', id: 'C', at: { x: 270, y: 62 }, label: 'C', draggable: true },
      { kind: 'point', id: 'P', at: invariantPoint, label: 'P' },
      { kind: 'polygon', id: 'triangle-ABC', points: ['A', 'B', 'C'] },
      { kind: 'midpoint', id: 'M', of: ['A', 'B'], label: 'M' },
      { kind: 'circle', id: 'source-circle', center: 'A', through: 'M' },
      { kind: 'homothety', id: 'H-A', center: 'O', source: 'A', factor: 0.58, label: 'Aₕ' },
      { kind: 'homothety', id: 'H-B', center: 'O', source: 'B', factor: 0.58, label: 'Bₕ' },
      { kind: 'homothety', id: 'H-C', center: 'O', source: 'C', factor: 0.58, label: 'Cₕ' },
      { kind: 'homothety', id: 'H-P', center: 'O', source: 'P', factor: 0.58, label: 'Pₕ' },
      { kind: 'polygon', id: 'homothetic-triangle', points: ['H-A', 'H-B', 'H-C'] },
      { kind: 'similarity', id: 'S-A', center: 'O', source: 'A', factor: 0.72, angle: 38, label: 'A′' },
      { kind: 'similarity', id: 'S-B', center: 'O', source: 'B', factor: 0.72, angle: 38, label: 'B′' },
      { kind: 'similarity', id: 'S-C', center: 'O', source: 'C', factor: 0.72, angle: 38, label: 'C′' },
      { kind: 'similarity', id: 'S-P', center: 'O', source: 'P', factor: 0.72, angle: 38, label: 'P′' },
      { kind: 'polygon', id: 'spiral-triangle', points: ['S-A', 'S-B', 'S-C'] },
      { kind: 'segment', id: 'spiral-ray-a', from: 'A', to: 'S-A' },
      { kind: 'segment', id: 'spiral-ray-b', from: 'B', to: 'S-B' },
      { kind: 'segment', id: 'spiral-point-path', from: 'P', to: 'S-P' },
      { kind: 'angle', id: 'spiral-angle', a: 'A', vertex: 'O', b: 'S-A' },
    ],
  }
  const simplex: SimplexObject = {
    id: 'simplex_projection',
    kind: 'simplex',
    weights: [bridgeMasses[0] * 0.82, bridgeMasses[1] * 0.82, bridgeMasses[2] * 0.82, 0.18],
    rotationX: -0.32,
    rotationY: 0.49,
    section: 0.46,
    denominator: 5,
    showLattice: true,
    bounds: { x: 1350, y: 810, width: 800, height: 450 },
    rotation: 0,
    author: 'agent',
    opacity: 1,
  }
  const numberTheory: NumberTheoryObject = {
    id: 'partition_observatory',
    kind: 'numberTheory',
    selectedN: 9,
    maxN: 24,
    finiteCutoff: 12,
    linkedSimplexId: simplex.id,
    revealTheorem: true,
    bounds: { x: 2445, y: 800, width: 815, height: 470 },
    rotation: 0,
    author: 'agent',
    opacity: 1,
  }

  const objects: WorldObject[] = [
    frame(OPENING_FRAME_ID, 'Gamma Function · Gamma Recurrence', [
      'opening_prompt', OPENING_ATTEMPT_ID, SOURCE_IMAGE_ID, HERO_EQUATION_ID,
    ], -860, 70, 820, 550),
    {
      id: 'opening_prompt',
      kind: 'text',
      text: 'Don’t finish it. Mark the exact place my reasoning breaks.',
      color: '#171713',
      fontSize: 22,
      bounds: { x: -815, y: 138, width: 700, height: 56 },
      rotation: 0,
      author: 'human',
      opacity: 1,
    },
    {
      id: OPENING_ATTEMPT_ID,
      kind: 'text',
      text: 'Γ(9/2) = ∫₀∞ x⁷ᐟ²e⁻ˣ dx\n= [−x⁷ᐟ²e⁻ˣ]₀∞ − (7/2)Γ(7/2)',
      color: '#171713',
      fontSize: 29,
      presentation: 'handwritten',
      bounds: { x: -815, y: 235, width: 700, height: 155 },
      rotation: -1.2,
      author: 'human',
      opacity: 1,
    },
    {
      id: SOURCE_IMAGE_ID,
      kind: 'image',
      src: 'handwriting://opening-attempt',
      alt: 'Captured handwritten Gamma recurrence',
      bounds: { x: -810, y: 430, width: 190, height: 135 },
      rotation: -1.2,
      author: 'human',
      opacity: 1,
    },
    {
      id: HERO_EQUATION_ID,
      kind: 'equation',
      latex: '\\Gamma\\!\\left(\\frac92\\right)=\\frac72\\Gamma\\!\\left(\\frac72\\right)',
      color: '#171713',
      bounds: { x: -585, y: 452, width: 465, height: 70 },
      rotation: 0,
      author: 'human',
      opacity: 0,
    },

    frame('gamma_probability_frame', 'Gamma Function · Gamma Density', [
      'eq_integrand', HERO_GRAPH_ID, 'gamma_bridge_equation',
    ], 220, 70, 860, 550),
    {
      id: 'eq_integrand',
      kind: 'equation',
      latex: 'g_a(x)=\\frac{x^{a-1}e^{-x}}{\\Gamma(a)},\\quad\\int_0^\\infty g_a(x)\\,dx=1',
      color: '#171713',
      bounds: { x: 270, y: 125, width: 730, height: 68 },
      rotation: 0,
      author: 'agent',
      opacity: 1,
    },
    {
      id: HERO_GRAPH_ID,
      kind: 'graph',
      equationId: 'eq_integrand',
      xDomain: [0, 16],
      yDomain: [0, 0.26],
      color: '#7c5cff',
      parameters: { a: shape, b: 6 },
      showTangentAt: shape - 1,
      shadeIntegral: [0, 6],
      visualization: 'gamma-density',
      binEdges,
      bounds: { x: 255, y: 195, width: 790, height: 375 },
      rotation: 0,
      author: 'agent',
      opacity: 1,
    },
    {
      id: 'gamma_bridge_equation',
      kind: 'equation',
      latex: 'w_j=\\int_{b_{j-1}}^{b_j}g_a(x)\\,dx,\\qquad \\sum_jw_j=1',
      color: '#7c5cff',
      bounds: { x: 490, y: 550, width: 430, height: 48 },
      rotation: 0,
      author: 'agent',
      opacity: 1,
    },

    frame('attention_geometry_frame', 'Tiny Transformer · Attention', [
      attention.id, 'attention_bridge_label',
    ], 1320, 70, 860, 550),
    {
      id: 'attention_bridge_label',
      kind: 'text',
      text: 'Edit any input or weight. Every downstream value recomputes immediately.',
      color: '#7c5cff',
      fontSize: 16,
      bounds: { x: 1380, y: 570, width: 700, height: 32 },
      rotation: 0,
      author: 'agent',
      opacity: 1,
    },
    attention,

    frame('train_from_scratch_frame', 'Tiny Transformer · Gradient Step', [
      training.id, 'training_truth_label',
    ], 2420, 70, 860, 550),
    {
      id: 'training_truth_label',
      kind: 'text',
      text: 'A complete tiny model: every visible update is a real numerical gradient step.',
      color: '#7c5cff',
      fontSize: 16,
      bounds: { x: 2490, y: 570, width: 700, height: 32 },
      rotation: 0,
      author: 'agent',
      opacity: 1,
    },
    training,

    frame('attention_barycentrics_frame', 'Olympiad Geometry · Barycentric Coordinates', [
      barycentric.id, 'barycentric_equation',
    ], -860, 750, 820, 550),
    {
      id: 'barycentric_equation',
      kind: 'equation',
      latex: 'P=\\alpha A+\\beta B+\\gamma C,\\quad \\alpha+\\beta+\\gamma=1',
      color: '#171713',
      bounds: { x: -725, y: 770, width: 540, height: 58 },
      rotation: 0,
      author: 'agent',
      opacity: 1,
    },
    barycentric,

    frame('spiral_similarity_frame', 'Olympiad Geometry · Spiral Similarity', [
      similarity.id, 'geometry_ratio', 'geometry_prompt', 'geometry_hint',
    ], 220, 750, 860, 550),
    {
      id: 'geometry_prompt',
      kind: 'text',
      text: 'The normalized point moves with the triangle.',
      color: '#171713',
      fontSize: 19,
      bounds: { x: 300, y: 770, width: 350, height: 40 },
      rotation: 0,
      author: 'human',
      opacity: 1,
    },
    {
      id: 'geometry_ratio',
      kind: 'equation',
      latex: 'S(X)=O+0.72R_{38^\\circ}(X-O)',
      color: '#7c5cff',
      bounds: { x: 650, y: 770, width: 400, height: 48 },
      rotation: 0,
      author: 'agent',
      opacity: 1,
    },
    {
      id: 'geometry_hint',
      kind: 'text',
      text: 'Drag A, B, C, or O. Ratios and equal angles recompute.',
      color: '#817d73',
      fontSize: 14,
      bounds: { x: 380, y: 1255, width: 540, height: 28 },
      rotation: 0,
      author: 'agent',
      opacity: 1,
    },
    similarity,

    frame('tetrahedral_probability_frame', 'Simplex and Partitions · Simplex', [
      simplex.id, 'simplex_equation',
    ], 1320, 750, 860, 550),
    {
      id: 'simplex_equation',
      kind: 'equation',
      latex: 'P=\\alpha A+\\beta B+\\gamma C+\\delta D,\\quad \\sum\\lambda_i=1',
      color: '#171713',
      bounds: { x: 1450, y: 770, width: 600, height: 56 },
      rotation: 0,
      author: 'agent',
      opacity: 1,
    },
    {
      id: 'simplex_section',
      kind: 'text',
      text: 'The moving triangular section remembers barycentrics.',
      color: '#7c5cff',
      fontSize: 15,
      bounds: { x: 1490, y: 1260, width: 520, height: 26 },
      rotation: 0,
      author: 'agent',
      opacity: 0,
    },
    simplex,

    frame('partition_observatory_frame', 'Simplex and Partitions · Integer Partitions', [
      numberTheory.id, 'partition_equation',
    ], 2420, 750, 860, 550),
    {
      id: 'partition_equation',
      kind: 'equation',
      latex: '\\prod_{m\\ge1}(1-q^m)^{-1}=\\sum_{N\\ge0}p(N)q^N',
      color: '#171713',
      bounds: { x: 2590, y: 765, width: 520, height: 52 },
      rotation: 0,
      author: 'agent',
      opacity: 1,
    },
    {
      id: 'partition_lattice',
      kind: 'text',
      text: 'compositions → quotient by order → partitions',
      color: '#817d73',
      fontSize: 14,
      bounds: { x: 2470, y: 1265, width: 390, height: 24 },
      rotation: 0,
      author: 'agent',
      opacity: 0,
    },
    {
      id: 'ramanujan_lanes',
      kind: 'equation',
      latex: 'p(5n+4)\\equiv0\\pmod5',
      color: '#7c5cff',
      bounds: { x: 2920, y: 1255, width: 280, height: 38 },
      rotation: 0,
      author: 'agent',
      opacity: 0,
    },
    numberTheory,
  ]

  return {
    version: 2,
    title: 'Mathburst',
    objects: Object.fromEntries(objects.map((object) => [object.id, object])),
    entities: {},
    bindings: {},
    timelines: {},
    order: objects.map((object) => object.id),
    selection: [],
    viewport: { x: 0, y: 0, zoom: 1 },
    history: [],
    future: [],
    activity: [],
    session: {
      attempts: 0,
      helpShown: [],
      currentMisconception: null,
      reconstructionStatus: 'source',
    },
    reconstruction: null,
  }
}
