import { useEffect, useRef, useState } from 'react'
import {
  CANONICAL_MATHOS_VIDEO_ID,
  mathosPlayerUrl,
  startMathosGeneration,
} from '../lib/mathosVideo'

type GenerationPhase = 'idle' | 'generating' | 'ready' | 'failed' | 'cancelled'

export default function MathosVideoPanel() {
  const canonicalUrl = mathosPlayerUrl(CANONICAL_MATHOS_VIDEO_ID)
  const [playerUrl, setPlayerUrl] = useState(canonicalUrl)
  const [sourceLabel, setSourceLabel] = useState('Generated by Mathos · canonical shared-path lesson')
  const [phase, setPhase] = useState<GenerationPhase>('idle')
  const [statusLines, setStatusLines] = useState<string[]>([])
  const generationRef = useRef<ReturnType<typeof startMathosGeneration> | null>(null)

  useEffect(() => () => generationRef.current?.cancel(), [])

  function generateFresh() {
    generationRef.current?.cancel()
    setPhase('generating')
    setStatusLines([])
    const generation = startMathosGeneration((update) => {
      setStatusLines(update.statusLines)
      if (update.requestId && update.fullReady) {
        setPlayerUrl(mathosPlayerUrl(update.requestId, 'full'))
        setSourceLabel('Generated by Mathos · fresh shared-path lesson')
      } else if (update.requestId && update.openingReady) {
        setPlayerUrl(mathosPlayerUrl(update.requestId, 'open'))
        setSourceLabel('Generated by Mathos · fresh opening preview')
      }
    })
    generationRef.current = generation
    generation.finished
      .then(() => setPhase('ready'))
      .catch((error: unknown) => {
        if (error instanceof DOMException && error.name === 'AbortError') return
        setPlayerUrl(canonicalUrl)
        setSourceLabel('Generated by Mathos · canonical shared-path lesson')
        setPhase('failed')
      })
  }

  function cancelGeneration() {
    generationRef.current?.cancel()
    generationRef.current = null
    setPlayerUrl(canonicalUrl)
    setSourceLabel('Generated by Mathos · canonical shared-path lesson')
    setPhase('cancelled')
  }

  return (
    <section className="mathos-video-panel" aria-labelledby="mathos-video-title">
      <div className="video-panel-head">
        <div>
          <p className="video-eyebrow">Mathos visual lesson</p>
          <h2 id="mathos-video-title">Watch both derivative paths meet.</h2>
        </div>
        <span className="video-real-badge"><i /> Real generation</span>
      </div>
      <div className="video-frame-wrap">
        <iframe
          src={playerUrl}
          title="Mathos shared-path calculus lesson"
          allow="autoplay; fullscreen"
          allowFullScreen
        />
        <a href={playerUrl} target="_blank" rel="noreferrer">Open player <span aria-hidden="true">↗</span></a>
      </div>
      <div className="video-detail-grid">
        <div>
          <p className="video-source">{sourceLabel}</p>
          <p className="video-summary">At x = 2, the product route contributes 36. The direct +a route contributes 4. Because both routes carry x’s effect into y, they add: 36 + 4 = 40.</p>
        </div>
        <div className="video-generation-controls">
          {phase === 'generating' ? (
            <button className="video-secondary-action" onClick={cancelGeneration}>Cancel generation</button>
          ) : (
            <button className="video-secondary-action" onClick={generateFresh}>Generate a fresh version</button>
          )}
          <div className="video-status" aria-live="polite">
            {statusLines.map((line) => <p key={line}>{line}</p>)}
            {phase === 'failed' && <p>Fresh generation is unavailable. The lesson still works.</p>}
            {phase === 'cancelled' && <p>Fresh generation cancelled. The canonical lesson is ready.</p>}
          </div>
        </div>
      </div>
      <details className="video-transcript">
        <summary>Read the lesson transcript</summary>
        <p>Start with a = x², b = 3x, and y = a·b + a. The value a reaches y in two ways: through a·b and directly through +a. The first path contributes 36 to dy/dx at x = 2. The direct path contributes da/dx = 2x = 4. Add both routes to get 40, then trace every shared-variable route on the fresh problem below.</p>
      </details>
    </section>
  )
}
