import { useEffect, useRef, useState } from 'react'
import {
  CANONICAL_MATHOS_VIDEO_ID,
  mathosPlayerUrl,
  startMathosGeneration,
} from '../lib/mathosVideo'

type GenerationPhase = 'idle' | 'generating' | 'ready' | 'failed' | 'cancelled'

export default function MathosVideoPanel() {
  const canonicalUrl = mathosPlayerUrl(CANONICAL_MATHOS_VIDEO_ID)
  const [playerUrl, setPlayerUrl] = useState(canonicalUrl)
  const [sourceLabel, setSourceLabel] = useState('Canonical shared-path lesson · ready now')
  const [phase, setPhase] = useState<GenerationPhase>('idle')
  const [statusLines, setStatusLines] = useState<string[]>([])
  const [openingReady, setOpeningReady] = useState(false)
  const generationRef = useRef<ReturnType<typeof startMathosGeneration> | null>(null)

  useEffect(() => () => generationRef.current?.cancel(), [])

  function generateFresh() {
    generationRef.current?.cancel()
    setPhase('generating')
    setStatusLines([])
    setOpeningReady(false)
    const generation = startMathosGeneration((update) => {
      setStatusLines(update.statusLines)
      if (update.requestId && update.fullReady) {
        setPlayerUrl(mathosPlayerUrl(update.requestId, 'full'))
        setSourceLabel('Fresh shared-path lesson · full video ready')
      } else if (update.requestId && update.openingReady) {
        setPlayerUrl(mathosPlayerUrl(update.requestId, 'open'))
        setOpeningReady(true)
        setSourceLabel('Fresh shared-path lesson · opening ready')
      }
    })
    generationRef.current = generation
    generation.finished
      .then(() => setPhase('ready'))
      .catch((error: unknown) => {
        if (error instanceof DOMException && error.name === 'AbortError') return
        setPlayerUrl(canonicalUrl)
        setSourceLabel('Canonical shared-path lesson · ready now')
        setOpeningReady(false)
        setPhase('failed')
      })
  }

  function cancelGeneration() {
    generationRef.current?.cancel()
    generationRef.current = null
    setPlayerUrl(canonicalUrl)
    setSourceLabel('Canonical shared-path lesson · ready now')
    setOpeningReady(false)
    setPhase('cancelled')
  }

  const mathVerified = statusLines.some((line) => line.includes('Verifying the math'))
  const scriptStarted = statusLines.some((line) => line.includes('Writing the script'))
  const fullReady = phase === 'ready'

  return (
    <section className="mathos-video-panel" aria-labelledby="mathos-video-title">
      <div className="video-panel-head">
        <div>
          <p className="video-eyebrow">Mathos · Video</p>
          <p className="video-context">You answered 36 <span>·</span> the direct +a route was missing</p>
          <h2 id="mathos-video-title">See both paths become 40.</h2>
        </div>
        <div className="video-speed-proof"><strong>5–10 sec</strong><span>Production first frame</span></div>
      </div>
      <ol className="video-build-steps" aria-label="Mathos video build progress">
        <li className={phase !== 'generating' || mathVerified || openingReady || fullReady ? 'done' : 'active'}><i />Verifying the math</li>
        <li className={phase !== 'generating' || scriptStarted || openingReady || fullReady ? 'done' : mathVerified ? 'active' : ''}><i />Writing the script</li>
        <li className={openingReady || fullReady || phase === 'idle' || phase === 'failed' || phase === 'cancelled' ? 'done' : ''}><i />Opening ready</li>
      </ol>
      <div className="video-frame-wrap">
        <iframe
          src={playerUrl}
          title="Mathos shared-path calculus lesson"
          allow="autoplay; fullscreen"
          allowFullScreen
        />
      </div>
      <div className="video-player-meta">
        <p className="video-source"><i />Generated by Mathos <span>·</span> {sourceLabel}</p>
        <a href={playerUrl} target="_blank" rel="noreferrer">Open full player <span aria-hidden="true">↗</span></a>
      </div>
      <div className="video-action-row">
        <p className="video-summary">The product route gives 36. The direct route gives 4. Both routes reach y, so 36 + 4 = 40.</p>
        <div className="video-generation-controls">
          {phase === 'generating' ? (
            <button className="video-secondary-action" onClick={cancelGeneration}>Cancel generation</button>
          ) : (
            <button className="video-secondary-action" onClick={generateFresh}>Generate a fresh version</button>
          )}
          <div className="video-status" aria-live="polite">
            {statusLines.map((line) => <p key={line}>{line}</p>)}
            {phase === 'failed' && <p>Fresh generation is unavailable. The lesson still works.</p>}
            {phase === 'cancelled' && <p>Fresh generation cancelled. The canonical lesson is ready.</p>}
          </div>
        </div>
      </div>
    </section>
  )
}
